/*
 * PowerStore REST API
 *
 * Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )
 *
 * OpenAPI spec version: 4.0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
        /// <summary>
        /// The process that initiated the data collection. Current values are:  * Manual - Initiated by user  * Scheduled - Initiated according to a predefined schedule  * System - Initiated by the system  * Health_Change - Initiated due to a change in the health status of the system  * Create_Cluster - Initiated as part of the create cluster operation  Was added in version 3.0.0.0.
        /// </summary>
        /// <value>The process that initiated the data collection. Current values are:  * Manual - Initiated by user  * Scheduled - Initiated according to a predefined schedule  * System - Initiated by the system  * Health_Change - Initiated due to a change in the health status of the system  * Create_Cluster - Initiated as part of the create cluster operation  Was added in version 3.0.0.0.</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum DatacollectionCreatorTypeEnum
        {
            
            /// <summary>
            /// Enum ManualEnum for Manual
            /// </summary>
            [EnumMember(Value = "Manual")]
            ManualEnum = 1,
            
            /// <summary>
            /// Enum ScheduledEnum for Scheduled
            /// </summary>
            [EnumMember(Value = "Scheduled")]
            ScheduledEnum = 2,
            
            /// <summary>
            /// Enum SystemEnum for System
            /// </summary>
            [EnumMember(Value = "System")]
            SystemEnum = 3,
            
            /// <summary>
            /// Enum HealthChangeEnum for Health_Change
            /// </summary>
            [EnumMember(Value = "Health_Change")]
            HealthChangeEnum = 4,
            
            /// <summary>
            /// Enum CreateClusterEnum for Create_Cluster
            /// </summary>
            [EnumMember(Value = "Create_Cluster")]
            CreateClusterEnum = 5
        }
}
