/*
 * PowerStore REST API
 *
 * Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )
 *
 * OpenAPI spec version: 4.0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
        /// <summary>
        /// Type of request that generated a migration recommendation. * Evacuate_Appliance - A recommendation to evacuate space by auto selecting storage objects from an appliance using specified size. * Evacuate_Objects - A recommendation to evacuate appliance by using specified objects.  Values was added in 2.0.0.0: Evacuate_Objects.
        /// </summary>
        /// <value>Type of request that generated a migration recommendation. * Evacuate_Appliance - A recommendation to evacuate space by auto selecting storage objects from an appliance using specified size. * Evacuate_Objects - A recommendation to evacuate appliance by using specified objects.  Values was added in 2.0.0.0: Evacuate_Objects.</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum MigrationRecommendationTypeEnum
        {
            
            /// <summary>
            /// Enum ApplianceEnum for Evacuate_Appliance
            /// </summary>
            [EnumMember(Value = "Evacuate_Appliance")]
            ApplianceEnum = 1,
            
            /// <summary>
            /// Enum ObjectsEnum for Evacuate_Objects
            /// </summary>
            [EnumMember(Value = "Evacuate_Objects")]
            ObjectsEnum = 2
        }
}
