/*
 * PowerStore REST API
 *
 * Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )
 *
 * OpenAPI spec version: 4.0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
        /// <summary>
        /// Type of the remote snapshot resource:  * volume - Remote snapshot is volume type.  * volume_group - Remote snapshot is volume_group type.  Was added in version 3.5.0.0.
        /// </summary>
        /// <value>Type of the remote snapshot resource:  * volume - Remote snapshot is volume type.  * volume_group - Remote snapshot is volume_group type.  Was added in version 3.5.0.0.</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum RemoteSnapshotResourceTypeEnum
        {
            
            /// <summary>
            /// Enum VolumeEnum for volume
            /// </summary>
            [EnumMember(Value = "volume")]
            VolumeEnum = 1,
            
            /// <summary>
            /// Enum VolumeGroupEnum for volume_group
            /// </summary>
            [EnumMember(Value = "volume_group")]
            VolumeGroupEnum = 2
        }
}
