/*
 * PowerStore REST API
 *
 * Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )
 *
 * OpenAPI spec version: 4.0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
        /// <summary>
        /// Supported import types for the source storage system. Values are:  * Agentless - The source array supports only agentless import.  * Non_Disruptive_And_Agentless - The source array supports both nondisruptive and agentless import.  * Not_Supported - The source array does not support import.  Was added in version 1.0.2.
        /// </summary>
        /// <value>Supported import types for the source storage system. Values are:  * Agentless - The source array supports only agentless import.  * Non_Disruptive_And_Agentless - The source array supports both nondisruptive and agentless import.  * Not_Supported - The source array does not support import.  Was added in version 1.0.2.</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum SupportedImportTypeEnum
        {
            
            /// <summary>
            /// Enum AgentlessEnum for Agentless
            /// </summary>
            [EnumMember(Value = "Agentless")]
            AgentlessEnum = 1,
            
            /// <summary>
            /// Enum NonDisruptiveAndAgentlessEnum for Non_Disruptive_And_Agentless
            /// </summary>
            [EnumMember(Value = "Non_Disruptive_And_Agentless")]
            NonDisruptiveAndAgentlessEnum = 2,
            
            /// <summary>
            /// Enum NotSupportedEnum for Not_Supported
            /// </summary>
            [EnumMember(Value = "Not_Supported")]
            NotSupportedEnum = 3
        }
}
