/*
 * PowerStore REST API
 *
 * Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )
 *
 * OpenAPI spec version: 4.0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Delete arguments. Was added in version 3.5.0.0.
    /// </summary>
    [DataContract]
    public partial class VolumeDelete : IEquatable<VolumeDelete>
    { 
        /// <summary>
        /// Delete the volume immediately and permanently, instead of moving the volume to the Recycle Bin. This is only valid for a volume and clone. A snapshot is immediately and permanently deleted if individually deleted. 
        /// </summary>
        /// <value>Delete the volume immediately and permanently, instead of moving the volume to the Recycle Bin. This is only valid for a volume and clone. A snapshot is immediately and permanently deleted if individually deleted. </value>

        [DataMember(Name="immediate")]
        public bool? Immediate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VolumeDelete {\n");
            sb.Append("  Immediate: ").Append(Immediate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((VolumeDelete)obj);
        }

        /// <summary>
        /// Returns true if VolumeDelete instances are equal
        /// </summary>
        /// <param name="other">Instance of VolumeDelete to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VolumeDelete other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Immediate == other.Immediate ||
                    Immediate != null &&
                    Immediate.Equals(other.Immediate)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Immediate != null)
                    hashCode = hashCode * 59 + Immediate.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(VolumeDelete left, VolumeDelete right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(VolumeDelete left, VolumeDelete right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
