/*
 * PowerStore REST API
 *
 * Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )
 *
 * OpenAPI spec version: 4.0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
        /// <summary>
        /// Usage of the certificate and the valid values are: * Server - Server Certificate * Client - Client Certificate * CA_Client_Validation - A CA certificate used to authenticate clients during an SSL handshake. * CA_Server_Validation - A CA certificate used to verify the server during an SSL handshake. 
        /// </summary>
        /// <value>Usage of the certificate and the valid values are: * Server - Server Certificate * Client - Client Certificate * CA_Client_Validation - A CA certificate used to authenticate clients during an SSL handshake. * CA_Server_Validation - A CA certificate used to verify the server during an SSL handshake. </value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum X509CertificateUsageTypeEnum
        {
            
            /// <summary>
            /// Enum ServerEnum for Server
            /// </summary>
            [EnumMember(Value = "Server")]
            ServerEnum = 1,
            
            /// <summary>
            /// Enum ClientEnum for Client
            /// </summary>
            [EnumMember(Value = "Client")]
            ClientEnum = 2,
            
            /// <summary>
            /// Enum CAClientValidationEnum for CA_Client_Validation
            /// </summary>
            [EnumMember(Value = "CA_Client_Validation")]
            CAClientValidationEnum = 3,
            
            /// <summary>
            /// Enum CAServerValidationEnum for CA_Server_Validation
            /// </summary>
            [EnumMember(Value = "CA_Server_Validation")]
            CAServerValidationEnum = 4
        }
}
