/*
 * PowerStore REST API
 *
 * Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )
 *
 * OpenAPI spec version: 4.0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class ImportHostInitiatorApiController : ControllerBase
    { 
        /// <summary>
        /// Collection Query
        /// </summary>
        /// <remarks>Query import host initiators.</remarks>
        /// <response code="200">Success</response>
        /// <response code="206">Partial content of import host initiator instance objects</response>
        [HttpGet]
        [Route("/api/rest/import_host_initiator")]
        [ValidateModelState]
        [SwaggerOperation("ImportHostInitiatorGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<ImportHostInitiatorInstance>), description: "Success")]
        [SwaggerResponse(statusCode: 206, type: typeof(List<ImportHostInitiatorInstance>), description: "Partial content of import host initiator instance objects")]
        public virtual IActionResult ImportHostInitiatorGet()
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<ImportHostInitiatorInstance>));

            //TODO: Uncomment the next line to return response 206 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(206, default(List<ImportHostInitiatorInstance>));

            string exampleJson = null;
            exampleJson = "{}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<List<ImportHostInitiatorInstance>>(exampleJson)
            : default(List<ImportHostInitiatorInstance>);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Instance Query
        /// </summary>
        /// <remarks>Query a specific import host initiator instance.</remarks>
        /// <param name="id">Unique identifier of the import host initiator to query.</param>
        /// <response code="200">Success</response>
        /// <response code="404">Not Found</response>
        [HttpGet]
        [Route("/api/rest/import_host_initiator/{id}")]
        [ValidateModelState]
        [SwaggerOperation("ImportHostInitiatorIdGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(ImportHostInitiatorInstance), description: "Success")]
        [SwaggerResponse(statusCode: 404, type: typeof(ErrorResponse), description: "Not Found")]
        public virtual IActionResult ImportHostInitiatorIdGet([FromRoute][Required]string id)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(ImportHostInitiatorInstance));

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404, default(ErrorResponse));

            string exampleJson = null;
            exampleJson = "{\"empty\": false}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<ImportHostInitiatorInstance>(exampleJson)
            : default(ImportHostInitiatorInstance);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
