/*
 * PowerStore REST API
 *
 * Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )
 *
 * OpenAPI spec version: 4.0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class ImportVmaxStorageGroupApiController : ControllerBase
    { 
        /// <summary>
        /// Collection Query
        /// </summary>
        /// <remarks>Query VMAX storage groups. Was added in version 3.0.0.0.</remarks>
        /// <response code="200">Success</response>
        /// <response code="206">Partial content of import vmax storage group instance objects</response>
        [HttpGet]
        [Route("/api/rest/import_vmax_storage_group")]
        [ValidateModelState]
        [SwaggerOperation("ImportVmaxStorageGroupGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<ImportVmaxStorageGroupInstance>), description: "Success")]
        [SwaggerResponse(statusCode: 206, type: typeof(List<ImportVmaxStorageGroupInstance>), description: "Partial content of import vmax storage group instance objects")]
        public virtual IActionResult ImportVmaxStorageGroupGet()
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<ImportVmaxStorageGroupInstance>));

            //TODO: Uncomment the next line to return response 206 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(206, default(List<ImportVmaxStorageGroupInstance>));

            string exampleJson = null;
            exampleJson = "{}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<List<ImportVmaxStorageGroupInstance>>(exampleJson)
            : default(List<ImportVmaxStorageGroupInstance>);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Instance Query
        /// </summary>
        /// <remarks>Query a specific VMAX storage group. Was added in version 3.0.0.0.</remarks>
        /// <param name="id">Unique identifier of a VMAX storage group. name:{name} can be used instead of {id}.</param>
        /// <response code="200">Success</response>
        /// <response code="404">Not Found</response>
        [HttpGet]
        [Route("/api/rest/import_vmax_storage_group/{id}")]
        [ValidateModelState]
        [SwaggerOperation("ImportVmaxStorageGroupIdGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(ImportVmaxStorageGroupInstance), description: "Success")]
        [SwaggerResponse(statusCode: 404, type: typeof(ErrorResponse), description: "Not Found")]
        public virtual IActionResult ImportVmaxStorageGroupIdGet([FromRoute][Required]string id)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(ImportVmaxStorageGroupInstance));

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404, default(ErrorResponse));

            string exampleJson = null;
            exampleJson = "{\"empty\": false}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<ImportVmaxStorageGroupInstance>(exampleJson)
            : default(ImportVmaxStorageGroupInstance);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Return snapshot policy
        /// </summary>
        /// <remarks>Return the snapshot policy associated with the specified VMAX storage group.  Was added in version 3.0.0.0.</remarks>
        /// <param name="id">Unique identifier of the VMAX storage group. name:{name} can be used instead of {id}.</param>
        /// <response code="200">Success</response>
        /// <response code="204">Success</response>
        /// <response code="400">Invalid request</response>
        /// <response code="404">Not Found</response>
        /// <response code="422">Operation Failed</response>
        [HttpPost]
        [Route("/api/rest/import_vmax_storage_group/{id}/import_snapshot_policy")]
        [ValidateModelState]
        [SwaggerOperation("ImportVmaxStorageGroupIdImportSnapshotPolicyPost")]
        [SwaggerResponse(statusCode: 200, type: typeof(ImportVmaxStorageGroupImportSnapshotPolicyResponse), description: "Success")]
        [SwaggerResponse(statusCode: 400, type: typeof(ErrorResponse), description: "Invalid request")]
        [SwaggerResponse(statusCode: 404, type: typeof(ErrorResponse), description: "Not Found")]
        [SwaggerResponse(statusCode: 422, type: typeof(ErrorResponse), description: "Operation Failed")]
        public virtual IActionResult ImportVmaxStorageGroupIdImportSnapshotPolicyPost([FromRoute][Required]string id)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(ImportVmaxStorageGroupImportSnapshotPolicyResponse));

            //TODO: Uncomment the next line to return response 204 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(204);

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default(ErrorResponse));

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404, default(ErrorResponse));

            //TODO: Uncomment the next line to return response 422 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(422, default(ErrorResponse));

            string exampleJson = null;
            exampleJson = "{\"empty\": false}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<ImportVmaxStorageGroupImportSnapshotPolicyResponse>(exampleJson)
            : default(ImportVmaxStorageGroupImportSnapshotPolicyResponse);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
