/*
 * PowerStore REST API
 *
 * Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )
 *
 * OpenAPI spec version: 4.0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Com.Dell.Emulator.Powerstore.Models
{ 
    /// <summary>
    /// Mapping of a source NAS server file interface to a local bond/FSN. Was added in version 3.0.0.0.
    /// </summary>
    [DataContract]
    public partial class FileImportSessionFileInterfaceMapping : IEquatable<FileImportSessionFileInterfaceMapping>
    { 
        /// <summary>
        /// Name of the source NAS Server file interface.
        /// </summary>
        /// <value>Name of the source NAS Server file interface.</value>
        [Required]
        
        [StringLength(255, MinimumLength=1)]
        [DataMember(Name="name")]
        public string Name { get; set; }

        /// <summary>
        /// Unique indentifier of the IP Port.
        /// </summary>
        /// <value>Unique indentifier of the IP Port.</value>
        [Required]
        
        [DataMember(Name="ip_port_id")]
        public string IpPortId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FileImportSessionFileInterfaceMapping {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  IpPortId: ").Append(IpPortId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((FileImportSessionFileInterfaceMapping)obj);
        }

        /// <summary>
        /// Returns true if FileImportSessionFileInterfaceMapping instances are equal
        /// </summary>
        /// <param name="other">Instance of FileImportSessionFileInterfaceMapping to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FileImportSessionFileInterfaceMapping other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) && 
                (
                    IpPortId == other.IpPortId ||
                    IpPortId != null &&
                    IpPortId.Equals(other.IpPortId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                    if (IpPortId != null)
                    hashCode = hashCode * 59 + IpPortId.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(FileImportSessionFileInterfaceMapping left, FileImportSessionFileInterfaceMapping right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(FileImportSessionFileInterfaceMapping left, FileImportSessionFileInterfaceMapping right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
