/*
 * PowerStore REST API
 *
 * Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )
 *
 * OpenAPI spec version: 4.0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Com.Dell.Emulator.Powerstore.Models
{ 
    /// <summary>
    /// Parameters of the virus_checker stop_scan operation. Specify either a list file_system_ids or is_stop_all&#x3D;true, not both.  Was added in version 3.0.0.0.
    /// </summary>
    [DataContract]
    public partial class FileVirusCheckerStopScan : IEquatable<FileVirusCheckerStopScan>
    { 
        /// <summary>
        /// List of specific filesystem ids where the virus scan must be stopped. Do not specify with is_stop_all&#x3D;true. 
        /// </summary>
        /// <value>List of specific filesystem ids where the virus scan must be stopped. Do not specify with is_stop_all&#x3D;true. </value>

        [DataMember(Name="file_system_ids")]
        public List<string> FileSystemIds { get; set; }

        /// <summary>
        /// True will stop all virus scan currently running on the storage resources of the associated NAS Server. Do not specify as true with file_system_ids. 
        /// </summary>
        /// <value>True will stop all virus scan currently running on the storage resources of the associated NAS Server. Do not specify as true with file_system_ids. </value>

        [DataMember(Name="is_stop_all")]
        public bool? IsStopAll { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FileVirusCheckerStopScan {\n");
            sb.Append("  FileSystemIds: ").Append(FileSystemIds).Append("\n");
            sb.Append("  IsStopAll: ").Append(IsStopAll).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((FileVirusCheckerStopScan)obj);
        }

        /// <summary>
        /// Returns true if FileVirusCheckerStopScan instances are equal
        /// </summary>
        /// <param name="other">Instance of FileVirusCheckerStopScan to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FileVirusCheckerStopScan other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    FileSystemIds == other.FileSystemIds ||
                    FileSystemIds != null &&
                    FileSystemIds.SequenceEqual(other.FileSystemIds)
                ) && 
                (
                    IsStopAll == other.IsStopAll ||
                    IsStopAll != null &&
                    IsStopAll.Equals(other.IsStopAll)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (FileSystemIds != null)
                    hashCode = hashCode * 59 + FileSystemIds.GetHashCode();
                    if (IsStopAll != null)
                    hashCode = hashCode * 59 + IsStopAll.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(FileVirusCheckerStopScan left, FileVirusCheckerStopScan right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(FileVirusCheckerStopScan left, FileVirusCheckerStopScan right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
