/*
 * PowerStore REST API
 *
 * Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )
 *
 * OpenAPI spec version: 4.0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Com.Dell.Emulator.Powerstore.Models
{ 
        /// <summary>
        /// Supported protocol. Available on the SFP hardware type. Current protocols are:  * Unknown - This SFP has unknown protocol support.  * FC - This SFP supports Fibre Channel.  * Ethernet - This SFP supports Ethernet.  * FC_Ethernet - This SFP supports Fibre Channel or Ethernet.  * SAS - This SFP supports SAS for connections to Expansion Enclosures. 
        /// </summary>
        /// <value>Supported protocol. Available on the SFP hardware type. Current protocols are:  * Unknown - This SFP has unknown protocol support.  * FC - This SFP supports Fibre Channel.  * Ethernet - This SFP supports Ethernet.  * FC_Ethernet - This SFP supports Fibre Channel or Ethernet.  * SAS - This SFP supports SAS for connections to Expansion Enclosures. </value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum HardwareSFPSupportedProtocolEnum
        {
            
            /// <summary>
            /// Enum UnknownEnum for Unknown
            /// </summary>
            [EnumMember(Value = "Unknown")]
            UnknownEnum = 1,
            
            /// <summary>
            /// Enum FCEnum for FC
            /// </summary>
            [EnumMember(Value = "FC")]
            FCEnum = 2,
            
            /// <summary>
            /// Enum EthernetEnum for Ethernet
            /// </summary>
            [EnumMember(Value = "Ethernet")]
            EthernetEnum = 3,
            
            /// <summary>
            /// Enum FCEthernetEnum for FC_Ethernet
            /// </summary>
            [EnumMember(Value = "FC_Ethernet")]
            FCEthernetEnum = 4,
            
            /// <summary>
            /// Enum SASEnum for SAS
            /// </summary>
            [EnumMember(Value = "SAS")]
            SASEnum = 5
        }
}
