/*
 * PowerStore REST API
 *
 * Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )
 *
 * OpenAPI spec version: 4.0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Com.Dell.Emulator.Powerstore.Models
{ 
        /// <summary>
        /// Protocol type of the import host initiator. Valid values are:  * Other - Protocol type is other.  * iSCSI - Protocol type is internet SCSI.  * FC - Protocol type is Fibre Channel.  * FCoE - Protocol type is Fibre Channel over Ethernet.  * Unknown - Protocol type is unknown to PowerStore. 
        /// </summary>
        /// <value>Protocol type of the import host initiator. Valid values are:  * Other - Protocol type is other.  * iSCSI - Protocol type is internet SCSI.  * FC - Protocol type is Fibre Channel.  * FCoE - Protocol type is Fibre Channel over Ethernet.  * Unknown - Protocol type is unknown to PowerStore. </value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum HostInitiatorProtocolTypeEnum
        {
            
            /// <summary>
            /// Enum OtherEnum for Other
            /// </summary>
            [EnumMember(Value = "Other")]
            OtherEnum = 1,
            
            /// <summary>
            /// Enum ISCSIEnum for iSCSI
            /// </summary>
            [EnumMember(Value = "iSCSI")]
            ISCSIEnum = 2,
            
            /// <summary>
            /// Enum FCEnum for FC
            /// </summary>
            [EnumMember(Value = "FC")]
            FCEnum = 3,
            
            /// <summary>
            /// Enum FCoEEnum for FCoE
            /// </summary>
            [EnumMember(Value = "FCoE")]
            FCoEEnum = 4,
            
            /// <summary>
            /// Enum UnknownEnum for Unknown
            /// </summary>
            [EnumMember(Value = "Unknown")]
            UnknownEnum = 5
        }
}
