/*
 * PowerStore REST API
 *
 * Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )
 *
 * OpenAPI spec version: 4.0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Com.Dell.Emulator.Powerstore.Models
{ 
        /// <summary>
        /// Entity that owns and manages this instance. The possible values are:   * User - This instance is managed by the end user.   * Metro - This instance is managed by the peer system where the policy was assigned, in a Metro Cluster configuration.   * Replication - This destination instance is managed by the source system in a Replication configuration.   * VMware_vSphere - This instance is managed by the system through VMware vSphere/vCenter.  Was added in version 3.0.0.0.
        /// </summary>
        /// <value>Entity that owns and manages this instance. The possible values are:   * User - This instance is managed by the end user.   * Metro - This instance is managed by the peer system where the policy was assigned, in a Metro Cluster configuration.   * Replication - This destination instance is managed by the source system in a Replication configuration.   * VMware_vSphere - This instance is managed by the system through VMware vSphere/vCenter.  Was added in version 3.0.0.0.</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum PolicyManagedByEnum
        {
            
            /// <summary>
            /// Enum UserEnum for User
            /// </summary>
            [EnumMember(Value = "User")]
            UserEnum = 1,
            
            /// <summary>
            /// Enum MetroEnum for Metro
            /// </summary>
            [EnumMember(Value = "Metro")]
            MetroEnum = 2,
            
            /// <summary>
            /// Enum ReplicationEnum for Replication
            /// </summary>
            [EnumMember(Value = "Replication")]
            ReplicationEnum = 3,
            
            /// <summary>
            /// Enum VMwareVSphereEnum for VMware_vSphere
            /// </summary>
            [EnumMember(Value = "VMware_vSphere")]
            VMwareVSphereEnum = 4
        }
}
