/*
 * PowerStore REST API
 *
 * Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )
 *
 * OpenAPI spec version: 4.0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Com.Dell.Emulator.Powerstore.Models
{ 
        /// <summary>
        /// The type of remote support that is configured. * SRS_Gateway - SRS Gateway without Remote Access * SRS_Gateway_Tier2 - SRS Gateway without Remote Access * SRS_Gateway_Tier3 - SRS Gateway with Remote Access * SRS_Integrated_Tier2 - SRS Integrated SRS without Remote Access * SRS_Integrated_Tier3 - SRS Integrated SRS with Remote Access * Disabled - SRS is Disabled  Was added in version 2.0.0.0.
        /// </summary>
        /// <value>The type of remote support that is configured. * SRS_Gateway - SRS Gateway without Remote Access * SRS_Gateway_Tier2 - SRS Gateway without Remote Access * SRS_Gateway_Tier3 - SRS Gateway with Remote Access * SRS_Integrated_Tier2 - SRS Integrated SRS without Remote Access * SRS_Integrated_Tier3 - SRS Integrated SRS with Remote Access * Disabled - SRS is Disabled  Was added in version 2.0.0.0.</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum RemoteSupportTypeEnum
        {
            
            /// <summary>
            /// Enum SRSGatewayEnum for SRS_Gateway
            /// </summary>
            [EnumMember(Value = "SRS_Gateway")]
            SRSGatewayEnum = 1,
            
            /// <summary>
            /// Enum SRSGatewayTier2Enum for SRS_Gateway_Tier2
            /// </summary>
            [EnumMember(Value = "SRS_Gateway_Tier2")]
            SRSGatewayTier2Enum = 2,
            
            /// <summary>
            /// Enum SRSGatewayTier3Enum for SRS_Gateway_Tier3
            /// </summary>
            [EnumMember(Value = "SRS_Gateway_Tier3")]
            SRSGatewayTier3Enum = 3,
            
            /// <summary>
            /// Enum SRSIntegratedTier2Enum for SRS_Integrated_Tier2
            /// </summary>
            [EnumMember(Value = "SRS_Integrated_Tier2")]
            SRSIntegratedTier2Enum = 4,
            
            /// <summary>
            /// Enum SRSIntegratedTier3Enum for SRS_Integrated_Tier3
            /// </summary>
            [EnumMember(Value = "SRS_Integrated_Tier3")]
            SRSIntegratedTier3Enum = 5,
            
            /// <summary>
            /// Enum DisabledEnum for Disabled
            /// </summary>
            [EnumMember(Value = "Disabled")]
            DisabledEnum = 6
        }
}
