/*
 * PowerStore REST API
 *
 * Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )
 *
 * OpenAPI spec version: 4.0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Com.Dell.Emulator.Powerstore.Models
{ 
        /// <summary>
        /// Severity level of current alerts for this entity and its contained objects. Values are:  * Clear - No alerts exist for this entity or contained/members.  * Information - The highest severity for this entity and all contained/members is Information.  * Minor - The highest severity for this entity and all contained/members is Minor.  * Major - The highest severity for this entity and all contained/members is Major.  * Critical - The highest severity for this entity and all contained/members is Critical.  * Unknown - The severity is unknown to PowerStore  Was added in version 1.0.2.
        /// </summary>
        /// <value>Severity level of current alerts for this entity and its contained objects. Values are:  * Clear - No alerts exist for this entity or contained/members.  * Information - The highest severity for this entity and all contained/members is Information.  * Minor - The highest severity for this entity and all contained/members is Minor.  * Major - The highest severity for this entity and all contained/members is Major.  * Critical - The highest severity for this entity and all contained/members is Critical.  * Unknown - The severity is unknown to PowerStore  Was added in version 1.0.2.</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum XtremIOObjectSeverityEnum
        {
            
            /// <summary>
            /// Enum ClearEnum for Clear
            /// </summary>
            [EnumMember(Value = "Clear")]
            ClearEnum = 1,
            
            /// <summary>
            /// Enum InformationEnum for Information
            /// </summary>
            [EnumMember(Value = "Information")]
            InformationEnum = 2,
            
            /// <summary>
            /// Enum MinorEnum for Minor
            /// </summary>
            [EnumMember(Value = "Minor")]
            MinorEnum = 3,
            
            /// <summary>
            /// Enum MajorEnum for Major
            /// </summary>
            [EnumMember(Value = "Major")]
            MajorEnum = 4,
            
            /// <summary>
            /// Enum CriticalEnum for Critical
            /// </summary>
            [EnumMember(Value = "Critical")]
            CriticalEnum = 5,
            
            /// <summary>
            /// Enum UnknownEnum for Unknown
            /// </summary>
            [EnumMember(Value = "Unknown")]
            UnknownEnum = 6
        }
}
