/*
 * PowerStore REST API
 *
 * Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )
 *
 * OpenAPI spec version: 4.0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using Com.Dell.Emulator.Powerstore.Attributes;

using Microsoft.AspNetCore.Authorization;
using Com.Dell.Emulator.Powerstore.Models;

namespace Com.Dell.Emulator.Powerstore.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class ImportNetappVolumeApiController : ControllerBase
    { 
        /// <summary>
        /// Collection Query
        /// </summary>
        /// <remarks>Query importable NetApp volumes. Was added in version 3.0.0.0.</remarks>
        /// <response code="200">Success</response>
        /// <response code="206">Partial content of import netapp volume instance objects</response>
        [HttpGet]
        [Route("/api/rest/import_netapp_volume")]
        [ValidateModelState]
        [SwaggerOperation("ImportNetappVolumeGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<ImportNetappVolumeInstance>), description: "Success")]
        [SwaggerResponse(statusCode: 206, type: typeof(List<ImportNetappVolumeInstance>), description: "Partial content of import netapp volume instance objects")]
        public virtual IActionResult ImportNetappVolumeGet()
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<ImportNetappVolumeInstance>));

            //TODO: Uncomment the next line to return response 206 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(206, default(List<ImportNetappVolumeInstance>));

            string exampleJson = null;
            exampleJson = "{}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<List<ImportNetappVolumeInstance>>(exampleJson)
            : default(List<ImportNetappVolumeInstance>);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Instance Query
        /// </summary>
        /// <remarks>Query a specific importable NetApp volume. Was added in version 3.0.0.0.</remarks>
        /// <param name="id">Unique identifier of the NetApp volume. name:{name} can be used instead of {id}.</param>
        /// <response code="200">Success</response>
        /// <response code="404">Not Found</response>
        [HttpGet]
        [Route("/api/rest/import_netapp_volume/{id}")]
        [ValidateModelState]
        [SwaggerOperation("ImportNetappVolumeIdGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(ImportNetappVolumeInstance), description: "Success")]
        [SwaggerResponse(statusCode: 404, type: typeof(ErrorResponse), description: "Not Found")]
        public virtual IActionResult ImportNetappVolumeIdGet([FromRoute][Required]string id)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(ImportNetappVolumeInstance));

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404, default(ErrorResponse));

            string exampleJson = null;
            exampleJson = "{\"empty\": false}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<ImportNetappVolumeInstance>(exampleJson)
            : default(ImportNetappVolumeInstance);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Return snapshot schedules
        /// </summary>
        /// <remarks>Return the snapshot schedules associated with the specified NetApp volume.  Was added in version 3.0.0.0.</remarks>
        /// <param name="id">Unique identifier of the NetApp volume. name:{name} can be used instead of {id}.</param>
        /// <response code="200">Success</response>
        /// <response code="204">Success</response>
        /// <response code="400">Invalid request</response>
        /// <response code="404">Not Found</response>
        /// <response code="422">Operation Failed</response>
        [HttpPost]
        [Route("/api/rest/import_netapp_volume/{id}/import_snapshot_schedules")]
        [ValidateModelState]
        [SwaggerOperation("ImportNetappVolumeIdImportSnapshotSchedulesPost")]
        [SwaggerResponse(statusCode: 200, type: typeof(ImportNetappVolumeImportSnapshotSchedulesResponse), description: "Success")]
        [SwaggerResponse(statusCode: 400, type: typeof(ErrorResponse), description: "Invalid request")]
        [SwaggerResponse(statusCode: 404, type: typeof(ErrorResponse), description: "Not Found")]
        [SwaggerResponse(statusCode: 422, type: typeof(ErrorResponse), description: "Operation Failed")]
        public virtual IActionResult ImportNetappVolumeIdImportSnapshotSchedulesPost([FromRoute][Required]string id)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(ImportNetappVolumeImportSnapshotSchedulesResponse));

            //TODO: Uncomment the next line to return response 204 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(204);

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default(ErrorResponse));

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404, default(ErrorResponse));

            //TODO: Uncomment the next line to return response 422 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(422, default(ErrorResponse));

            string exampleJson = null;
            exampleJson = "{\"empty\": false}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<ImportNetappVolumeImportSnapshotSchedulesResponse>(exampleJson)
            : default(ImportNetappVolumeImportSnapshotSchedulesResponse);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
